name: mb.com
channels:
  - defaults
dependencies:
  - python=3.5
  - asn1crypto=0.24.0
  - ca-certificates=2018.03.07
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0
  - cryptography=2.2.2
  - Cython=0.28.3
  - idna=2.6
  - intel-openmp=2018.0.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpq=10.3
  - mkl=2018.0.2
  - mkl_fft=1.0.1
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.14.2
  - openssl=1.0.2o
  - pandas=0.23.0
  - pip=10.0.1
  - psycopg2=2.7.4
  - pycparser=2.18
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python-dateutil=2.7
  - pytz=2018.4
  - readline=7.0
  - requests=2.18
  - setuptools=39.1.0
  - six=1.11.0
  - sqlalchemy=1.2.7
  - sqlite=3.23.1
  - tk=8.6.7
  - urllib3=1.22
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - pgxnclient==1.2.1
